name: "nightly"

on:
  schedule:
    - cron: '0 0 * * *'
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:

    - name: Checkout Source
      uses: actions/checkout@v2
      if: ${{ github.repository_owner == 'albatrossflavour' }}

    - name: Install PDK
      if: ${{ github.repository_owner == 'albatrossflavour' }}
      run: |
        wget https://apt.puppet.com/puppet-tools-release-focal.deb
        sudo dpkg -i puppet-tools-release-focal.deb
        sudo apt-get update
        sudo apt-get install pdk
        sudo chmod -R go-w /opt /home/linuxbrew

    - name: Run tests
      if: ${{ github.repository_owner == 'albatrossflavour' }}
      run: |
        export PATH=/opt/puppetlabs/pdk/bin:$PATH
        make
